name: Week 3 Lab - DevOps and Testing with Copilot
description: Hands-on Copilot lab for Week 3 covering CI/CD automation, infrastructure as code, and test generation
title: "Week 3 Lab: DevOps & Testing - <Your Name>"
labels: ["lab", "week-3"]
body:
  - type: markdown
    attributes:
      value: |
        ## Goal
        Learn to use GitHub Copilot for DevOps automation and testing to streamline software delivery and improve code reliability.

  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      options:
        - label: Read `Workshops/Week3/1-DevOps-Automation.md`
        - label: Read `Workshops/Week3/2-Testing-and-Quality-Assurance.md`
        - label: Complete the hands-on lab in `Workshops/Week3/3-Week3-Lab.md`
        - label: Review prompt examples in `Workshops/Week3/4-Week3-Prompts.md`
    validations:
      required: true

  - type: checkboxes
    id: devops_topics
    attributes:
      label: Which DevOps topics did you practice?
      options:
        - label: CI/CD pipeline generation (GitHub Actions)
        - label: Dockerfile creation and optimisation
        - label: Kubernetes manifests (Deployment, Service, ConfigMap)
        - label: Terraform/Infrastructure as Code
        - label: Docker Compose configuration
        - label: Pre-deployment validation scripts
        - label: Environment-specific configurations

  - type: checkboxes
    id: testing_topics
    attributes:
      label: Which testing topics did you practice?
      options:
        - label: Unit test generation for existing code
        - label: Test coverage improvement
        - label: Parameterised/data-driven tests
        - label: Mock and stub generation
        - label: Test framework conversion (e.g., Selenium → Cypress)
        - label: Integration test creation
        - label: Edge case and boundary testing

  - type: textarea
    id: pipeline_example
    attributes:
      label: CI/CD pipeline or IaC you created
      description: Paste an example of a pipeline, Dockerfile, or infrastructure config Copilot helped generate
      placeholder: |
        name: CI Pipeline
        on: [push, pull_request]
        jobs:
          build:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
              ...
    validations:
      required: true

  - type: textarea
    id: test_example
    attributes:
      label: Test code Copilot generated
      description: Paste an example of test code that Copilot generated well
      placeholder: |
        describe('calculateTotal', () => {
          it('should return sum of items', () => {
            // Test generated by Copilot...
          });
        });

  - type: dropdown
    id: devops_confidence
    attributes:
      label: How confident are you using Copilot for DevOps tasks?
      options:
        - "Very confident - ready to use for real pipelines"
        - "Fairly confident - can create basic configurations"
        - "Somewhat confident - need more practice"
        - "Not confident - still learning the concepts"
    validations:
      required: true

  - type: dropdown
    id: testing_confidence
    attributes:
      label: How confident are you using Copilot for test generation?
      options:
        - "Very confident - significantly improves my test coverage"
        - "Fairly confident - helpful for standard test cases"
        - "Somewhat confident - useful but requires editing"
        - "Not confident - tests often need major rework"
    validations:
      required: true

  - type: textarea
    id: best_prompt
    attributes:
      label: Best prompt you used (paste it here)
      description: Share a DevOps or testing prompt that worked particularly well
      placeholder: |
        Example: "Generate a GitHub Actions workflow that builds a Node.js app, runs tests with coverage, and deploys to Azure App Service on main branch pushes"
    validations:
      required: true

  - type: dropdown
    id: time_impact
    attributes:
      label: Time impact compared to writing configs/tests manually
      options:
        - "Saved significant time (30+ minutes)"
        - "Saved some time (10-30 minutes)"
        - "About the same"
        - "Took longer (learning curve)"
    validations:
      required: true

  - type: textarea
    id: worked
    attributes:
      label: What worked well?
      placeholder: "Which DevOps or testing tasks did Copilot handle particularly well?"
    validations:
      required: true

  - type: textarea
    id: challenges
    attributes:
      label: What was challenging?
      placeholder: "Where did Copilot's suggestions need significant modification? Any incorrect configurations?"
    validations:
      required: true

  - type: dropdown
    id: coverage_improvement
    attributes:
      label: Did Copilot help improve your test coverage?
      options:
        - "Yes - significantly (added 20%+ coverage)"
        - "Yes - moderately (added 10-20% coverage)"
        - "Yes - slightly (added <10% coverage)"
        - "No - didn't focus on coverage this week"
        - "Not applicable"

  - type: textarea
    id: security_validation
    attributes:
      label: Security or validation improvements (optional)
      description: Did you add any security scanning, validation steps, or quality gates to your pipeline?
      placeholder: |
        - Added npm audit step
        - Included SAST scanning
        - Added Dockerfile linting...

  - type: textarea
    id: pr_link
    attributes:
      label: PR link (if applicable)
      placeholder: "Paste the PR URL here"

  - type: textarea
    id: next_steps
    attributes:
      label: What will you apply in your daily work?
      description: Which DevOps or testing techniques from Week 3 will you start using regularly?
